# ЁЯУж рж╕ржорж╕рзНржд ржЖрж░рзНржЯрж┐ржлрзНржпрж╛ржХрзНржЯ (ржпрзЗ ржлрзЛрж▓рзНржбрж╛рж░рзЗ рж╕ржм intermediate output/store рж╣ржмрзЗ) тАУ рждрж╛рж░ ржорзВрж▓ рж░рзБржЯ ржбрж┐рж░рзЗржХрзНржЯрж░рж┐
artifacts_root: artifacts

# ЁЯН╖ Data Ingestion рж╕ржВржХрзНрж░рж╛ржирзНржд рж╕ржм рж╕рзЗржЯрж┐ржВрж╕
data_ingestion:
  # ЁЯУБ ржбрзЗржЯрж╛ ржЗржиржЬрзЗрж╢ржи ржлрзЗржЬрзЗрж░ ржорзВрж▓ ржбрж┐рж░рзЗржХрзНржЯрж░рж┐ ржпрзЗржЦрж╛ржирзЗ рж╕ржмржХрж┐ржЫрзБ рж╕рзЗржн рж╣ржмрзЗ
  root_dir: artifacts/data_ingestion

  # ЁЯМР ржбрзЗржЯрж╛рж░ рж╕рзЛрж░рзНрж╕ рж▓рж┐ржВржХ (ZIP ржлрж╛ржЗрж▓ тАУ ржЧрж┐ржЯрж╣рж╛ржм ржерзЗржХрзЗ winequality dataset)
  source_URL: https://github.com/entbappy/Branching-tutorial/raw/master/winequality-data.zip

  # ЁЯТ╛ рж▓рзЛржХрж╛рж▓ рж╕рж┐рж╕рзНржЯрзЗржорзЗ ржбрзЗржЯрж╛ ржлрж╛ржЗрж▓ ржХрзЛржерж╛рзЯ рж╕рзЗржн рж╣ржмрзЗ (ZIP ржЖржХрж╛рж░рзЗ)
  local_data_file: artifacts/data_ingestion/data.zip

  # ЁЯУВ ZIP ржлрж╛ржЗрж▓ ржЖржиржЬрж┐ржк ржХрж░рж╛рж░ ржкрж░ ржбрзЗржЯрж╛ ржХрзЛржерж╛рзЯ ржПржХрзНрж╕ржЯрзНрж░рзНржпрж╛ржХрзНржЯ рж╣ржмрзЗ
  unzip_dir: artifacts/data_ingestion



data_validation:
  root_dir: artifacts/data_validation   # ЁЯУБ ржпрзЗржЦрж╛ржирзЗ ржбрзЗржЯрж╛ ржнрзНржпрж╛рж▓рж┐ржбрзЗрж╢ржи рж╕ржВржХрзНрж░рж╛ржирзНржд рж╕ржм ржлрж╛ржЗрж▓ ржерж╛ржХржмрзЗ
  unzip_data_dir: artifacts/data_ingestion/winequality-red.csv   # ЁЯЧВя╕П ржЖржиржЬрж┐ржк ржХрж░рж╛ CSV ржбрзЗржЯрж╛рж░ ржЕржмрж╕рзНржерж╛ржи
  STATUS_FILE: artifacts/data_validation/status.txt   # ЁЯУД рж╕рзНржЯрзНржпрж╛ржЯрж╛рж╕ рж░рж╛ржЦрж╛рж░ ржЬржирзНржп ржПржХржЯрж┐ ржЯрзЗржХрзНрж╕ржЯ ржлрж╛ржЗрж▓ (ржпрзЗржоржиржГ validation рж╣рзЯрзЗржЫрзЗ ржХрж┐ржирж╛)
 

# ЁЯФД ржбрзЗржЯрж╛ ржЯрзНрж░рж╛ржирзНрж╕ржлрж░ржорзЗрж╢ржи ржХржиржлрж┐ржЧрж╛рж░рзЗрж╢ржи ржЕржВрж╢

data_transformation:
  root_dir: artifacts/data_transformation    # ЁЯЧВя╕П ржПржЦрж╛ржирзЗ ржЯрзНрж░рж╛ржирзНрж╕ржлрж░рзНржо ржХрж░рж╛ ржбрзЗржЯрж╛ ржмрж╛ рж░рж┐рж▓рзЗржЯрзЗржб ржлрж╛ржЗрж▓ржЧрзБрж▓рзЛ рж╕ржВрж░ржХрзНрж╖ржг рж╣ржмрзЗ
  data_path: artifacts/data_ingestion/winequality-red.csv   # ЁЯУД ржЗржиржкрзБржЯ рж╣рж┐рж╕рзЗржмрзЗ ржмрзНржпржмрж╣рзГржд рж╣ржмрзЗ ржПржЗ CSV ржбрзЗржЯрж╛рж╕рзЗржЯ (ржЗржиржЬрзЗрж╕рзНржЯрзЗржб ржбрзЗржЯрж╛)


